CREATE PROCEDURE [dbo].[ADD_EMPLOYEE]
	@STAFFID NVARCHAR(10), 
	@GIVENNAME NVARCHAR(15), 
	@SURNAME NVARCHAR(20)
AS
	BEGIN TRY 

		INSERT INTO EMPLOYEE(STAFFID, GIVENNAME, SURNAME) VALUES (@STAFFID, @GIVENNAME, @SURNAME)

	END TRY
	BEGIN CATCH
		BEGIN 
          DECLARE @ERRORMESSAGE NVARCHAR(MAX) = ERROR_MESSAGE();
          THROW 50000, @ERRORMESSAGE, 1
        END;
	END CATCH
RETURN 0
